name: CI

on:
  push:
    branches:
      - main

jobs:
  # ESlint Check
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint

  # Prettier Check
  prettier:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install  
      - name: Run Prettier check
        run: npx prettier --check "**/*.js"
      - name: Fix code style issues with Prettier
        run: npx prettier --write "**/*.js"